name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # 监听主分支的 push 操作

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create Static Files
      run: |
        mkdir public
        cp index.html public/
        cp README.zh.html public/
        cp README.en.html public/
        touch public/.nojekyll

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
